# Generated by Django 3.0.11 on 2021-01-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDailyReport',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_order_count', models.PositiveIntegerField(default=0)),
                ('total_order_qty', models.PositiveIntegerField(default=0)),
                ('total_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
        ),
    ]
